version: "3.9"
services:
    api:
        build: FinalProject/
        container_name: api
        ports:
            - 5001:5001
        networks:
            blocknet:
    mock:
        build: BlockChainMock/
        container_name: blockchainmock
        ports:
            - 5002:5002
        networks:
            blocknet:
    db:
        build: database/
        container_name: go_database
        ports:
            - 5432:5432
        networks:
            blocknet:
networks:
    blocknet:
        driver: bridge
        enable_ipv6: false
        ipam:
            driver: default
            config:
                - subnet: 172.0.0.0/16
                  gateway: 172.0.0.1